### ISSUE TITLE
Allow user to have a more advanced search functionality 

### ISSUE THREAD

**Issue by FottyM** [kenigbolo/Chafity#86]

**Comment by Kennu76** [comment]
The detailed requirement that this issue is linked with: [FR#3](https://github.com/kenigbolo/Chafity/wiki/Functional-Requirements#3-the-website-allows-users-to-search-for-other-users-through-the-search-tool-users-can-be-searched-by-name-or-company-and-search-can-be-filtered-by-influencers-uc3-issue13)
