### ISSUE TITLE
Bug fix for charity Model

### ISSUE THREAD

**Issue by kenigbolo** [kenigbolo/Chafity#98]
Currently the database requires a user ID for a charity to be saved however this shouldn't be the case. Make changes to reflect the independence of the charities model

**Comment by kenigbolo** [comment]
Bug fixed, kindly close issue

**Comment by Kennu76** [comment]
The detailed requirement that this issue is linked with: [FR#6](https://github.com/kenigbolo/Chafity/wiki/Functional-Requirements#6the-website-allows-passive-charity-account-to-be-created-which-do-not-send-or-recieve-messages-the-charities-collect-donations-that-are-made-when-users-communicate-with-eachother-uc6)
